language: cpp

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost1.59-all-dev

compiler:
    - gcc
    - clang

before_script:
  - mkdir boost
  - cd boost
  - wget https://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.bz2/download
  - tar jxf download
  - sudo cp -r boost_1_59_0/boost /usr/include/
    - mkdir build
    - cd build
    - cmake ..

script: 
  - mkdir build
  - cd build
  - cmake ..
  - make
