language: cpp

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost1.59-all-dev

compiler:
    - gcc
    - clang

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make
