language: cpp

sudo: required
dist: trusty

compiler:
    - gcc

before_install:
  - mkdir boost
  - cd boost
  - wget https://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.bz2/download
  - tar jxf download
  - sudo cp -r boost_1_59_0/boost /usr/include/
  - cd ../
  - mkdir lemon
  - cd lemon
  - wget http://lemon.cs.elte.hu/pub/sources/lemon-1.2.4.tar.gz
  - tar -zxf lemon-1.2.4.tar.gz
  - cd lemon-1.2.4
  - ./configure
  - make
  - sudo make install
  - cd ../../

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make
  - cd tests
  - ctest

